In [1]:
import tensorflow as tf

# Create a tensorflow object 
tf_constant = tf.constant("Hello world !")

with tf.Session() as sess:
    output = sess.run(tf_constant)
    print (output)

b'Hello world !'


In [5]:
a = tf.constant(2)
b = tf.constant(3)

c = tf.add(a, b)
d = tf.multiply(a, b)
with tf.Session() as sess:
    output = sess.run(c)
    output2 = sess.run(d)
    print (output, output2)


5 6


In [12]:
# Other ways to perform basic operations
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

c = tf.add(a, b)
d = tf.multiply(a, b)

with tf.Session() as sess:
    output = sess.run(c, feed_dict={a:3, b:5})
    output2 = sess.run(d, feed_dict={a:3, b:5})
    print (output, output2)


8.0


In [15]:
# Tensors can be string as well
x = tf.placeholder(tf.string, name='string_variable_x')
print (x)
with tf.Session() as sess:
    output = sess.run(x, feed_dict={x: 'Test string'}) # Here first argument x can be string
    print (output)

Tensor("string_variable_x:0", dtype=string)
Test string


In [16]:
import tensorflow as tf

# Convert the following to TensorFlow:
x = 10
y = 2
z = x/y - 1

# TODO: Print z from a session
x = tf.constant(x)
y = tf.constant(y)
z = tf.divide(x, y)

with tf.Session() as sess:
    output = sess.run(z)
    test = sess.run(x)
    print (output)
    print (test)
# z = tf.subtract(-tf.constant(1))


5.0
10


In [24]:
# Matrices in tensorflow
import numpy as np
matrix1 = tf.constant(np.random.randint(0,10,size=(3,2)))
print (matrix1)
matrix2 = tf.constant(np.random.randint(0,10, size=(2,3)))
print (matrix2)
matrix = tf.matmul(matrix1, matrix2)
# Printing always is done using the Session
with tf.Session() as sess:
    print(sess.run(matrix))


Tensor("Const_16:0", shape=(3, 2), dtype=int32)
Tensor("Const_17:0", shape=(2, 3), dtype=int32)
[[ 56  76  39]
 [ 56  32  40]
 [ 76 100  53]]
